version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    ports:
      - 3005:3000
    user: '104'
    networks:
      - grafana_network
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.8.5
    container_name: influxdb_local
    restart: always
    ports:
      - 8087:8086
    networks:
      - grafana_network
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_USER=arun2493
      - INFLUXDB_USER_PASSWORD=Welcome@2021

networks:
  grafana_network:
volumes:
  grafana_data:
  influxdb_data:

